### ISSUE TITLE
请求安全联系方式和反馈问题

### ISSUE THREAD

**Issue by kosakuraiori** [wanmin-books/wanmin-books#1]
提示：由于自闭症的缘故，可能我说的话比较令人难以理解。

能否在发布书籍时提供一份“HTML”版本或者“Word（doc，不是docx，或者odt）”版本？
[https://zh.anarchistlibraries.net/library/red-russia-travel-notes](url)
以这个链接为例：中文无治图书馆使用的Amuse Wiki软件无法兼容Markdown格式，AmuseWiki也无法直接导入PDF文件直接翻录成电子版本。
这导致我们在录入贵组织的书籍时特别困难。

第二个问题：你们有什么安全的一对一联系方式吗？
例如：电子邮箱、Signal、SimpleX chat、Briar。
方便后续一对一交流。

**Comment by xitieshiz2** [comment]
1.Markdown可以直接渲染为html，事实上Markdown内部直接使用html元素都没问题，如果您需要，我可以每次发布新书的时候发一份渲染成html的版本给您。
2.我们目前没有什么传统意义上“安全”的私信联系方式，不过有电子邮箱，您可以送信至wanmin-books@outlook.com，私信我们的推特账户或者我们在a.nti.social上的账户。
如果还是需要安全的联系，可以联系我的Session账户，留下您的电子邮箱，我会把Session码发过去。

另外冒昧问一下，您是中文无治图书馆的管理员？如果是的话，麻烦私信介绍下管理员平时都在哪交流和活动？

**Comment by kosakuraiori** [comment]
> 1.Markdown可以直接渲染为html，事实上Markdown内部直接使用html元素都没问题，如果您需要，我可以每次发布新书的时候发一份渲染成html的版本给您。 2.我们目前没有什么传统意义上“安全”的私信联系方式，不过有电子邮箱，您可以送信至[wanmin-books@outlook.com](mailto:wanmin-books@outlook.com)，私信我们的推特账户或者我们在a.nti.social上的账户。 如果还是需要安全的联系，可以联系我的Session账户，留下您的电子邮箱，我会把Session码发过去。
> 
> 另外冒昧问一下，您是中文无治图书馆的管理员？如果是的话，麻烦私信介绍下管理员平时都在哪交流和活动？

是的，我是其中一位管理员，我无法透露具体人数，但目前活跃的管理员只有我一个人了。

可以，我可以使用Markdown to HTML转换器来实现这个目的。

一封来自iorikosakura2000【@】gmail.com的邮件已经发送，那上面有我的Session ID和另外一个更安全的电子邮箱的地址。
